#ifndef CODIGO_ERROR_H
#define CODIGO_ERROR_H

enum _error
{
	NO_HAY_ERROR,
	ERROR_RUTA_COMIENZA_MAL,
	ERROR_NO_SE_ENCUENTRA_RUTA,
	ERROR_YA_EXISTE_SUBDIRECTORIO,
	ERROR_NO_SE_PUEDE_CREAR_DIR_RAIZ,
	ERROR_DIRECTORIO_NOMBRE_INCORRECTO, 
	ERROR_PARAMETRO_DESCONOCIDO
};
typedef enum _error TipoError;

#endif